spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.113/sell?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /ordering

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/ordinging